### ISSUE TITLE
예외처리 관련

### ISSUE THREAD

**Issue by Nekopoly** [LiteHell/hitomi.la#2]
이 모듈이 네트워크 또는 파싱문제시 앱이 다운되는
치명적인 문제를 끼침.

**Comment by Nekopoly** [comment]
예: 404 오류 가 발생 할때 html 그대로 가져와서 파싱에 문제를 일으킴.

**Comment by Nekopoly** [comment]
/home/NekoPoly/backend/node_modules/hitomi.la/lib/list.js:19        var count = pattern.exec(body)[1];
                                      ^

TypeError: Cannot read property '1' of null
    at Request._callback (/home/NekoPoly/backend/node_modules/hitomi.la/lib/list.js:19:39)
    at Request.self.callback (/home/NekoPoly/backend/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)                               at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/NekoPoly/backend/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/NekoPoly/backend/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
nekopoly@irc:~/backend$ node app.js

6시5분 쯤 타입에러가 발생함.

**Comment by Nekopoly** [comment]
.jpg"},{"height":300,"width":212,"name":"012.jpg"},{"name":"013.jpg","width":212,"height":300},{"name":"014.jpg","height":300,"width":212},{"name":"015.jpg","width":212,"height":300},{"width":212,"height":300,"name":"016.jpg"},{"height":300,"width":212,"name":"017.jpg"},{"height":300,"width":212,"name":"018.jpg"},{"name":"019.jpg","height":300,"width":212},{"width":212,"height":300,"name":"020.jpg"},{"width":212,"height":300,"name":"021.jpg"},{"name":"022.jpg","width":212,"height":300},{"name":"023.jpg","width":212,"height":

SyntaxError: Unexpected token = in JSON at position 0
    at Object.parse (native)
    at Request._callback (/home/NekoPoly/backend/node_modules/hitomi.la/lib/getImageLinks.js:13:27)
    at Request.self.callback (/home/NekoPoly/backend/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/NekoPoly/backend/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/NekoPoly/backend/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
이하 이미지를 불러오는 코드도 마찬가지.
